spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: ${AUTHENTICATION_DB}
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      repositories:
        type: reactive
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cheonlijip.fyczq.mongodb.net/cheonlijip?retryWrites=true&w=majority
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul
server:
  port: ${SERVER_PORT}
  shutdown: graceful
kakao:
  property:
    authorization-prefix: ${KAKAO_AUTHORIZATION_PREFIX}
    base-url: ${KAKAO_BASE_URL}
    search-endpoint: ${KAKAO_KEYWORD_SEARCH_ENDPOINT}
    address-endpoint: ${KAKAO_ADDRESS_SEARCH_ENDPOINT}
    rest-api-key: ${KAKAO_REST_API_KEY}
jwt:
  secret-key: ${JWT_SECRET_KEY}